# .github/workflows/sync.yml

name: Sync upstream Firecracker

on:
  schedule:
    - cron: '0 0 * * *'      # runs every day at midnight UTC
  workflow_dispatch:        # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # fetch all history for all branches

      - name: Configure git for merge
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/firecracker-microvm/firecracker.git
          git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Push changes back to your fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
